stages:
  - build
  - deploy

build_test:
  image: node:8.10.0
  tags:
    - frontend
  # Cache libraries in between jobs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  stage: build
  script:
    - npm install
    - npm run test
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

build_production:
  image: node:8.10.0
  tags:
    - frontend
  # Cache libraries in between jobs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  stage: build
  script:
    - npm install
    - npm run prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - production

deploy_testing:
  image: alpine
  tags:
    - frontend
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\nHost 192.168.1.166 \nPort 2223" > ~/.ssh/config
    - rsync -rav --delete dist/ jti@192.168.1.166:/var/www/jti/data/www/jti-frontend.ibec.systems
  only:
    - master
    
deploy_production:
  image: alpine
  tags:
    - jti_terminal
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_PROD" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\nHost 109.233.110.131 \nPort 2223" > ~/.ssh/config
    - rsync -rav --delete dist/ partner360@109.233.110.131:/home/partner360/www/partner360.kz/
  only:
    - production